1:
  command_first: "post twitter status "
  hint_first: "< your status message >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
2:
  command_first: "post facebook status "
  hint_first: "< your status message >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
3:
  command_first: "find place "
  hint_first: "< place name >"
  param_first: ""
  command_second: "near "
  hint_second: "< address or zipcode >"
  param_second: ""
4:
  command_first: "search "
  hint_first: "< query >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
6:
  command_first: "read twitter stream"
  hint_first: ""
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
7:
  command_first: "login twitter"
  hint_first: ""
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
8:
  command_first: "login facebook"
  hint_first: ""
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
9:
  command_first: "list friends"
  hint_first: ""
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
10:
  command_first: "weather "
  hint_first: "< address or zipcode >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
11:
  command_first: "calculate "
  hint_first: "< expression >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
12:
  command_first: "select "
  hint_first: "< facebook friend name >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
13:
  command_first: "say "
  hint_first: "< your message >"
  param_first: ""
  command_second: "to "
  hint_second: "< facebook friend name >"
  param_second: ""
15:
  command_first: "direction from "
  hint_first: "< address >"
  param_first: ""
  command_second: "to "
  hint_second: "< address >"
  param_second: "" 
16:
  command_first: "meaning "
  hint_first: "< word >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
17:
  command_first: "define "
  hint_first: "< word >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
18:
  command_first: "what is "
  hint_first: "< term / query >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
19:
  command_first: "lookup "
  hint_first: "< term / query >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
20:
  command_first: "dictionary "
  hint_first: "< word >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
21:
  command_first: "flickr recent"
  hint_first: ""
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""
24:
  command_first: "search twitter "
  hint_first: "< term (optional: from:user to:user) >"
  param_first: ""
  command_second: ""
  hint_second: ""
  param_second: ""